backend:
  name: git-gateway
  repo: codecatur-website/xhayden.github.io
  branch: master
  site_domain: codedecatur.org

publish_mode: editorial_workflow
site_url: https://codedecatur.org
media_folder: src/images
public_folder: /images
---
slug: "/blog/code-decatur-reborn"
date: "2020-07-18"
title: "Hello, Code Decatur."
author: "Hayden Carpenter"
featuredImage: "../images/codecatur.png"
---
collections:
  - name: "blog"
    label: "Blog Post"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "featuredImage", name: "cover", widget: "image", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Slug (link)",
          name: "slug",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Hide", name: "hide", widget: "boolean", required: false }